# Generated by Django 4.0.1 on 2022-01-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Askstories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=30)),
                ('descendants', models.IntegerField()),
                ('id_askstories', models.IntegerField()),
                ('kids', models.TextField()),
                ('score', models.IntegerField()),
                ('text', models.TextField()),
                ('time', models.IntegerField()),
                ('title', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Jobstories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=30)),
                ('id_jobstories', models.IntegerField()),
                ('score', models.IntegerField()),
                ('text', models.TextField()),
                ('time', models.IntegerField()),
                ('title', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Newstories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=30)),
                ('descendants', models.IntegerField()),
                ('id_newstories', models.IntegerField()),
                ('kids', models.TextField()),
                ('score', models.IntegerField()),
                ('text', models.TextField()),
                ('time', models.IntegerField()),
                ('title', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Showstories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=30)),
                ('descendants', models.IntegerField()),
                ('id_showstories', models.IntegerField()),
                ('kids', models.TextField()),
                ('score', models.IntegerField()),
                ('text', models.TextField()),
                ('time', models.IntegerField()),
                ('title', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
    ]
