# Generated by Django 4.0.2 on 2022-02-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product_id',
            field=models.PositiveIntegerField(),
        ),
    ]
