# Generated by Django 4.0.2 on 2022-02-07 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfGuitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(default='description')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categoryofguitar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
