# Generated by Django 4.0.2 on 2022-02-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_basket_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='path_img',
            field=models.FileField(null=True, upload_to='uploads/%m/'),
        ),
    ]
