# Generated by Django 4.0.2 on 2022-02-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_guitar_path_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='path_img',
            field=models.FileField(default='', upload_to='uploads/%m/'),
        ),
    ]
